### ISSUE TITLE
Checksums for Shush binaries.

### ISSUE THREAD

**Issue by treacher** [realestate-com-au/shush#26]
Hi there,

I was wondering whether it would be possible for checksums to be provided with Shush releases so that we're able to verify the contents before using the binary.

Kind of similar to this project: https://github.com/weaveworks/eksctl/releases

Our security team gave us a recommendation that we should verify the contents of binaries prior to making them widely available within our organisation.

Thank you so much for Shush, we use it everyday and we love it ❤️

**Comment by tigris** [comment]
Good idea. Thanks!

This is now done for the latest `1.5.2` release, and will be automated from now on.

Fixed in 12d43707363c89c2a1f40c5c13815d10d08309f9
