### ISSUE TITLE
Provide arm64 build

### ISSUE THREAD

**Issue by toothbrush** [realestate-com-au/shush#29]
Hey folks, i'm investigating moving some of our workload to AWS Graviton (aka arm64) instances, and we use Dockerised `shush` a lot.

I grabbed a checkout this repo `master` and did a `docker build .` on an arm64 instance, and it all worked perfectly.  I could contribute a patch at some point but i thought i'd make this issue as a reminder/placeholder.  Also, i'm unfamiliar with REA's build pipeline which makes it a bit harder since i think the big change will be there.

Thanks for providing this tool! 🙌

**Comment by tigris** [comment]
Thanks for the report @toothbrush. We unfortunately didn't have any release automation in place for this tool.

I've generated some basic automation using our internal tooling here, and fired off a release of 1.5.1 which should habe the docker images you require.

**Comment by toothbrush** [comment]
Ah, no problem – sorry for the hassle!  Thank you! 🙏
