### ISSUE TITLE
Shush lacks support for ECS task roles

### ISSUE THREAD

**Issue by pvdvreede** [realestate-com-au/shush#4]
Hi @mdub we are using shush inside a ecs task container and it does not seem to be able to get access to what that ecs task role allows.

I know from previous attempts that if the AWS SDK is not new enough, ecs task roles are not supported. Do you know if the go AWS SDK support ecs tasks roles? Have you or anyone else had luck with sush 1.3.0 and ecs task roles?

**Comment by mdub** [comment]
I haven't tried it on ECS, @pvdvreede.  But it appears the version of `aws-sdk-go` used in 1.3.0 lacks support.

I'll update the SDK, and make a patch release.

**Comment by mdub** [comment]
New `v1.3.1` binaries are up, @pvdvreede:

* https://github.com/realestate-com-au/shush/releases/tag/v1.3.1

Can you test, and let me know how it goes?

**Comment by pvdvreede** [comment]
Thanks! Ill let you know!

**Comment by pvdvreede** [comment]
👍  That has got it working!
