### ISSUE TITLE
Arguments to the command after `shush exec` are parsed by shush instead

### ISSUE THREAD

**Issue by amcinnes** [realestate-com-au/shush#8]
When I do this:
```
shush exec ls -la
```
I get
```
Incorrect Usage: flag provided but not defined: -la

NAME:
   shush exec - Execute a command

USAGE:
   shush exec [command options] [arguments...]

OPTIONS:
   --prefix value  environment variable prefix (default: "KMS_ENCRYPTED_")
```

I would expect shush to know that any command-line options passed after the command belong to the command and not to shush itself.

i.e. I would expect `shush exec ls -la` to do the same as `shush exec -- ls -la`

**Comment by mdub** [comment]
I think this is default behaviour - looking for options anywhere in the command-line - of the option-parsing library we use, [urfave/cli](https://github.com/urfave/cli). 

I agree it's surprising, and annoying, for a "command shim" tool like `shush`. Hopefully there's a way to disable that behaviour. If not, we could switch to [ogier/pflag](https://github.com/ogier/pflag), which I know can be configure to work how we want.

**Comment by mdub** [comment]
Ironically, my Ruby command-line parsing library, [clamp](https://github.com/mdub/clamp), has an [open issue](https://github.com/mdub/clamp/issues/71) requesting support for the behaviour we _don't_ want here :-)
